export const api = [
  {
    id: 0,
    qty: null,
    title: 'Lake Inniscarra, Ireland— Pyramid',
    name: 'lake-inniscarra',
    timer: '30:53',
    distance: '6,248 M',
  },
  {
    id: 1,
    qty: 9,
    title: 'Performance Series',
    name: 'performance-series',
    timer: null,
    distance: null,
  },
  {
    id: 2,
    qty: null,
    title: 'Slow Pulls and Fast Intervals',
    name: 'slow-pulls',
    timer: "44:13",
    distance: "9,948 M",
  },
  {
    id: 3,
    qty: 12,
    title: '20 Minutes to Toned',
    name: '20-minutes-to-toned',
    timer: null,
    distance: null,
  },
  {
    id: 4,
    qty: null,
    title: 'Charles Race, Boston, Massachusetts',
    name: 'charles-race',
    timer: "36:22",
    distance: "8,648 M",
  },
  {
    id: 5,
    qty: 12,
    title: 'Full-Body HIIT Series',
    name: 'full-body-hiit',
    timer: null,
    distance: null,
  },
  {
    id: 6,
    qty: null,
    title: 'Kafue River, Zambia—Power Stroke Pyramid',
    name: 'kafue-river',
    timer: "22:22",
    distance: "4,660 M",
  },
  {
    id: 7,
    qty: 16,
    title: 'Shred & Burn Series',
    name: 'shred-and-burn',
    timer: null,
    distance: null,
  },
]