export const workouts = [
  {
    id: 0,
    name: 'lake-inniscarra',
    title: 'Lake Inniscarra, Ireland— Pyramid',
    time: '30:53',
    dist: '6,248 M',
    workouts: null,
  },
  {
    id: 1,
    name: 'performance-series',
    title: 'Performance Series',
    time: null,
    dist: null,
    workouts: 9,
  },
  {
    id: 2,
    name: 'slow-pulls',
    title: 'Slow Pulls and Fast Intervals',
    time: "44:13",
    dist: "9,948 M",
    workouts: null,
  },
  {
    id: 3,
    name: '20-minutes-to-toned',
    title: '20 Minutes to Toned',
    time: null,
    dist: null,
    workouts: 12,
  },
  {
    id: 4,
    name: 'charles-race',
    title: 'Charles Race, Boston, Massachusetts',
    time: "36:22",
    dist: "8,648 M",
    workouts: null,
  },
  {
    id: 5,
    name: 'full-body-hiit',
    title: 'Full-Body HIIT Series',
    time: null,
    dist: null,
    workouts: 12,
  },
  {
    id: 6,
    name: 'kafue-river',
    title: 'Kafue River, Zambia—Power Stroke Pyramid',
    time: "22:22",
    dist: "4,660 M",
    workouts: null,
  },
  {
    id: 7,
    name: 'shred-and-burn',
    title: 'Shred & Burn Series',
    time: null,
    dist: null,
    workouts: 16,
  },
]